version: '3'

services:
  fastapi:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8008:8008
    volumes:
      - $HOME/.cache/huggingface/transformers:/root/.cache/huggingface/transformers
