version: '3'

services:
  fastapi:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - $HOME/.cache/huggingface/transformers:/root/.cache/huggingface/transformers
